Ext.define('Ext.locale.tr.pivot.plugin.configurator.Column', {
    override: 'Ext.pivot.plugin.configurator.Column',

    sumText:                    'Topla',
    avgText:                    'Ort',
    countText:                  'Sayı',
    minText:                    'En Az',
    maxText:                    'En Fazla',
    groupSumPercentageText:     'Grup toplam yüzdesi',
    groupCountPercentageText:   'Grup sayı yüzdesi',
    varText:                    'Var',
    varPText:                   'Varp',
    stdDevText:                 'StdDev',
    stdDevPText:                'StdDevp',

    sortAscText:                "A'dan Z'ye sırala",
    sortDescText:               "Z'den A'ya sırala",
    sortClearText:              'Sıralamayı iptal et',
    clearFilterText:            '"{0}" filtresini temizle',
    labelFiltersText:           'Etiket filtresi',
    valueFiltersText:           'Değer filtresi',
    equalsText:                 'Eşit...',
    doesNotEqualText:           'Eşit değil...',
    beginsWithText:             '... ile başlayan',
    doesNotBeginWithText:       '... ile başlamayan',
    endsWithText:               '... ile biten',
    doesNotEndWithText:         '... ile bitmeyen',
    containsText:               'İçinde ... olan',
    doesNotContainText:         'İçinde ... olmayan',
    greaterThanText:            '... dan büyük',
    greaterThanOrEqualToText:   '... dan büyük ve eşit',
    lessThanText:               '... den küçük',
    lessThanOrEqualToText:      '... den küçük ve eşit',
    betweenText:                '... arasında',
    notBetweenText:             '... arasında olmayan',
    top10Text:                  'En yüksek 10...',

    equalsLText:                'Eşit',
    doesNotEqualLText:          'Eşit değil',
    beginsWithLText:            'ile başlayan',
    doesNotBeginWithLText:      'ile başlamayan',
    endsWithLText:              'ile biten',
    doesNotEndWithLText:        'ile bitmeyen',
    containsLText:              'İçeren',
    doesNotContainLText:        'İçermeyen',
    greaterThanLText:           'den büyük',
    greaterThanOrEqualToLText:  'den büyük ve eşit',
    lessThanLText:              'den küçük',
    lessThanOrEqualToLText:     'den küçük ve eşit',
    betweenLText:               'arasında',
    notBetweenLText:            'arasında değil',
    top10LText:                 'En yüksek 10...',
    topOrderTopText:            'En yüksek',
    topOrderBottomText:         'Alt',
    topTypeItemsText:           'Öğeler',
    topTypePercentText:         'Yüzde',
    topTypeSumText:             'Toplam'
});